blank_issues_enabled: false
contact_links:
- name: CloudFoundry slack
  url: https://cloudfoundry.slack.com
  about: For help or questions about this component, you can reach the maintainers on Slack
